services:
  app:
    build: .
    restart: unless-stopped
    # please only use volume binding in development environment.
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_APP_ENVIRONMENT=${FASTAPI_APP_ENVIRONMENT}
      - SESSION_SECRET=${SESSION_SECRET}
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@${DB_HOST:-postgres}:${DB_PORT:-5432}/${POSTGRES_DB:-db}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}"]
      interval: 10s
      timeout: 5s
      retries: 3

  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - dbgate_data:/root/.dbgate
    environment:
      - CONNECTIONS=con1

      - LABEL_con1=PostgreSQL
      - SERVER_con1=${DB_HOST:-postgres}
      - USER_con1=${POSTGRES_USER:-user}
      - PASSWORD_con1=${POSTGRES_PASSWORD:-password}
      - PORT_con1=${DB_PORT:-5432}
      - ENGINE_con1=postgres@dbgate-plugin-postgres
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    profiles: ["redis"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    restart: unless-stopped
    profiles: ["minio"]
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data

  lakefs:
    image: treeverse/lakefs
    restart: unless-stopped
    profiles: ["lakefs"]
    ports:
      - "8001:8000"
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_ENCRYPT_SECRET:-some-random-secret}
      - LAKEFS_DATABASE_TYPE=local
    volumes:
      - lakefs_data:/home/lakefs

volumes:
  postgres_data:
  dbgate_data:
  redis_data:
  minio_data:
  lakefs_data:
